API_BASE_URL="https://api.alpaca.markets"
ML_MODEL="catboost"
SUB_VERSION="beta"
RUN_SCHEDULE="off"
SENTIMENT_OFFSET_MINUTES=1
REWRITE="off"
META_MODEL_TYPE="cat"
USE_FULL_SHARES=False
DISABLE_PRED_CLOSE=True
STATIC_TICKERS="QQQ"
BACKTEST_TICKER="TSLA"
USE_SHORT=False
BAR_TIMEFRAME="4Hour"
N_BARS=10000
ROLLING_CANDLES=0
HORIZON=1
NEWS_MODE="on"
TRADE_LOGIC=25
AI_TICKER_COUNT=0
MAX_TICKERS=3
DISCORD_MODE="off"

if SUB_VERSION == "old":
    USE_META_LABEL=False
